import { getPrinters } from '../config/store';
import { printHtmlToDevice } from './html-print';

/**
 * Print an A4 report (Daily, Sales, Expense, etc.) on the configured reports
 * printer. The HTML is generated by the renderer and sent over IPC.
 */
export async function printA4Report(html: string, opts: { landscape?: boolean } = {}): Promise<void> {
  const slot = (await getPrinters()).reports;
  if (slot.mode === 'disabled') {
    throw new Error('Reports printer is not configured. Set it in Printer Settings.');
  }
  if (slot.mode === 'network') {
    throw new Error('Reports printer cannot use network mode. Pick an OS-installed printer.');
  }
  await printHtmlToDevice(html, slot.deviceName, {
    pageSize: 'A4',
    landscape: opts.landscape ?? false,
  });
}
